M48
; DRILL file {KiCad (7.0.0)} date Wed Jan  8 17:10:45 2025
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-01-08T17:10:45+03:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(7.0.0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.200
%
G90
G05
T1
X196.89Y-113.51
X202.67Y-113.51
T2
X224.375Y-62.425
T0
M30
